version: '3.7'
services:
  # server:
  #   build: .
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on:
  #     - redis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
